### PR TITLE
Weeder on CI

### PR DESCRIPTION
**Pull request by Anviking**
#48.

### CODE REVIEW

**Comment by Anviking** [comment]
Runs fine, but we get

- Would be nice to move to a separate stage or something so you see exactly what failed on the Github-checks-view.
- `weeder .` fails
<details>
= Package cardano-wallet =

== Section exe:wal-integr-test ==
Weeds exported
* Error
  - CantFindAddress
  - HttpClientError
  - UnexpectedAccountBalance
  - WalletPassMissing
  - showConstr
* HardwareWalletSpecs
  - postUnsignedTransactionTest
  - signAndPostTransactionTest
  - uniqueNewWallet
* Types
  - ActionWalletState
* Util
  - createAddress
  - genesisRef
  - isGenesisWallet
  - isLockedWallet
  - noLongerThan
  - oneSecond
  - randomRestoreWallet
  - shouldReturnRight

== Section test:unit ==
Excessive other-modules entry
* Cardano.Wallet.Kernel.BIP39Spec
* Util.Distr
* Util.GenHash
* Util.Histogram
* Util.MultiSet
* Util.QuickCheck
* Util.Range
Redundant build-depends entry
* filepath
* optparse-applicative
Unused import
* Test.Spec.Addresses
  - Test.Spec.Wallets
Weeds exported
* Arbitrary
  - slotIdGen
* Cardano.Wallet.Kernel.BIP39Spec
  - TestVector
  - spec
* Test.Spec.CoinSelection.Generators
  - AtLeast
  - Exactly
  - GenerationTarget
  - StakeGenOptions
  - genUtxo
  - toLovelaces
* UTxO.ToCardano.Interpreter
  - popIntCheckpoint
  - pushCheckpoint
  - runIntBoot
  - runIntT
* Util.Buildable.Hspec
  - shouldNotBe
  - valid
* Util.Buildable.QuickCheck
  - forAllShrink
* Util.Distr
  - Constant
  - Distribution
  - Erlang
  - Exponential
  - FreqDistr
  - Gumbel
  - Normal
  - Uniform
  - drawFromDistr
  - drawFromDistr'
* Util.GenHash
  - GenHash
  - GenHashT
  - evalGenHashT
  - genHash
  - runGenHashT
  - withHash
* Util.Histogram
  - Bin
  - BinSize
  - Count
  - Histogram
  - add
  - discretize
  - empty
  - filterBins
  - filterCounts
  - fromList
  - fromMap
  - insert
  - insertMany
  - max
  - nLargestBins
  - range
  - readFile
  - splitGivenRanges
  - splitRanges
  - toList
  - toMap
  - unionWith
  - writeFile
* Util.MultiSet
  - MultiSet
  - empty
  - findMin
  - fromList
  - medianWithDefault
  - singleton
  - size
  - union
  - unions
* Util.QuickCheck
  - LiftQuickCheck
  - liftQuickCheck
* Util.Range
  - SplitRanges
  - containedIn
  - hi
  - lo
  - rangeWithWidth
  - renderSplitAxis
  - splitXRanges
  - splitYRange
  - width
  - x
  - y
* Wallet.Abstract
  - applyBlocks
* Wallet.Inductive
  - inductiveInit
* Wallet.Inductive.Cardano
  - EquivalenceNotChecked
  - EquivalenceViolationEvidence
  - EventCallbacks
  - NotEquivalent
  - interpretT
* Wallet.Inductive.Generator
  - gegsNextHash
  - gegsPending
  - genEventTree
* Wallet.Inductive.Interpreter
  - InvalidPending
* Wallet.Inductive.Invariants
  - InvariantNotChecked
  - InvariantViolation
  - InvariantViolationEvidence
  - NotAllSatisfy
  - NotDisjoint
  - NotEqual
  - NotSubsetOf
  - invariant
* Wallet.Inductive.Validation
  - InductiveInvalidApplyBlock
  - InductiveInvalidBoot
  - InductiveInvalidNewPendingAlreadySpent
  - InductiveInvalidNewPendingNotOurs
* Wallet.Prefiltered
  - mkWallet
* Wallet.Rollback.Basic
  - State
  - initState
  - mkWallet
  - stateCheckpoints
  - stateCurrent
* Wallet.Rollback.Full
  - Checkpoint
  - State
  - checkpointExpected
  - checkpointIncr
  - checkpointPending
  - checkpointUtxo
  - checkpointUtxoBalance
  - initState
  - mkWallet
  - stateCheckpoints
  - stateCurrent
  - stateIncr
</details>


They can be ignored, but I think they should be fixed. _Looking_

**Comment by KtorZ** [comment]
We should find a way to get this reported to us somehow without making the build fail. 
I think it's fine to run it only nightly, and ultimately have a report in Slack (via a slack-bot or something). 

For now, let's just have that as a nightly build and allow failure. We can go and lookup the build log manually when needed.

**Comment by Anviking** [comment]
Not yet motivated thought: I wonder if we wouldn't ultimately want to have weeder and coverage both in https://blog.github.com/2018-05-07-introducing-checks-api/

For now: I think it could be simple to create a Github App and just `curl` a request to the Github API containing the `weeder` output…

**Comment by KtorZ** [comment]
We've already spent too much time on setting up CI and we have to move on. We'll write a few sentences in the `consequences` retrospective for those issues. And possible open new issues as follow-ups. 
For now, let's consider the work on CI, done.

**Review by KtorZ — APPROVED** [review]

**Pull request merged**
