### PR TITLE
Cleanup NodeStateAdaptor further

### PR DESCRIPTION
**Pull request by Anviking**
<p align="right">#87</p>

# Overview

-  ~Removed `withNodeState`~ No I didn't
- [x] Removed  `getSlotStart :: SlotId -> m (Either UnknownEpoch Timestamp)`
- [x] Removed `defaultGetCreationTimestamp`
- [x] Removed `getNodeSyncProgress`

# Comments

- Depends on #218
- I previously believed `getSlotStart` was used in explorer, but it is not from the `NodeStateAdaptor`.

### CODE REVIEW

**Comment by Anviking** [comment]
Can be squash-merged (I believe that's a button-click?); I prefer to start with small self-contained commits.

**Comment by KtorZ** [comment]
The diff looks weird. Like replaying the same commits. May you rebase on-top of `develop` :thinking: ?

**Comment by Anviking** [comment]
@KtorZ will do after #218 is merged, to lessen merge conflicts. 

Squashed though, if you want to have a look before that:

~https://github.com/input-output-hk/cardano-wallet/pull/246/commits/d567b89bad7d87e7f8816a2b2e1287cee14662e2~

Sorry!

**Comment by Anviking** [comment]
(I should investigate CI failures first though)

I think I ran the wrong `Ghcid` command 😥

**Review by KtorZ — APPROVED** [review]

**Pull request merged**
