### PR TITLE
Aggressive `withMaxSuccess` limits in `wallet-unit-tests`

### PR DESCRIPTION
**Pull request by Anviking**
All about making it run faster.

#38

### CODE REVIEW

**Comment by Anviking** [comment]
Oops wrong commit

**Comment by KtorZ** [comment]
You're still not running unit-tests on the CI, you know :no_mouth:

**Comment by Anviking** [comment]
@KtorZ There's a plan for that da8738b50bbec10da61ddf8b2d78b46551c7967f :)

**Comment by KtorZ** [comment]
Merged Manually.

**Pull request closed without merging**
